// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDnxBt_6eHnpVA8-SK4V9_OgTOqY6Z86k',
    appId: '1:89454843187:web:ec53d172c588eb0fbf5a46',
    messagingSenderId: '89454843187',
    projectId: 'ai-app-57b46',
    authDomain: 'ai-app-57b46.firebaseapp.com',
    storageBucket: 'ai-app-57b46.firebasestorage.app',
    measurementId: 'G-55J54DG797',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxAPirC3qYdSKOZi9VBiFDIlQ7CA156bY',
    appId: '1:89454843187:android:a1d4b770799a87a2bf5a46',
    messagingSenderId: '89454843187',
    projectId: 'ai-app-57b46',
    storageBucket: 'ai-app-57b46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB3yi5gQnL_9Y4aKFAvy5BFY2MilymHfk',
    appId: '1:89454843187:ios:9b38006e267aea69bf5a46',
    messagingSenderId: '89454843187',
    projectId: 'ai-app-57b46',
    storageBucket: 'ai-app-57b46.firebasestorage.app',
    iosBundleId: 'com.example.aiApp',
  );
}
